export const DEFAULT_CHANNELS = [
  'shroud',
  'tarik',
  'summit1g'
];

export const DEFAULT_SCRIPT_TEMPLATE = `#!/bin/bash
# Generated by StreamWatcher
# Usage: ./launch.sh
open {{url}}
# Or use mpv:
# mpv {{url}}
`;

export const POLLING_INTERVALS = [1, 5, 10, 15, 30];
